#include "_type/type.mime.h"

_fromStr<_mime> string2mimeType = {
	{ "directory" , _mime::directory } ,
	{ "image/jpeg" , _mime::image_jpeg } ,
	{ "image/png" , _mime::image_png } ,
	{ "image/gif" , _mime::image_gif } ,
	{ "image/bmp" , _mime::image_bmp } ,
	{ "image/ico" , _mime::image_ico } ,
	{ "text/plain" , _mime::text_plain } ,
	{ "text/html" , _mime::text_html } ,
	{ "text/xml" , _mime::text_xml } ,
	{ "text/x-ini" , _mime::text_x_ini } ,
	{ "font/opentype" , _mime::font_opentype } ,
	{ "font/truetype" , _mime::font_truetype } ,
	{ "audio/mpeg" , _mime::audio_mpeg } ,
	{ "audio/wav" , _mime::audio_wav } ,
	{ "audio/x-aiff" , _mime::audio_x_aiff } ,
	{ "audio/x-midi" , _mime::audio_x_midi } ,
	{ "audio/x-mpegurl" , _mime::audio_x_mpegurl } ,
	{ "audio/x-mod" , _mime::audio_x_mod } ,
	{ "application/microsoft-installer" , _mime::application_microsoft_installer } ,
	{ "application/octet-stream" , _mime::application_octet_stream } ,
	{ "application/x-lua-bytecode" , _mime::application_x_lua_bytecode } ,
	{ "application/x-ms-shortcut" , _mime::application_x_ms_shortcut } ,
	{ "application/x-ms-registry" , _mime::application_x_ms_registry } ,
	{ "application/x-internet-shortcut" , _mime::application_x_internet_shortcut } ,
	{ "application/x-nintendo-ds-rom" , _mime::application_x_nintendo_ds_rom } ,
	{ "application/x-nintendo-gba-rom" , _mime::application_x_nintendo_gba_rom } ,
	{ "application/x-bat" , _mime::application_x_bat }
};

// File Extensions#
_fromStr<_mime> extension2mimeType = {
	{ "jpg" , _mime::image_jpeg } ,
	{ "jpeg" , _mime::image_jpeg } ,
	{ "png" , _mime::image_png } ,
	{ "gif" , _mime::image_gif } ,
	{ "bmp" , _mime::image_bmp } ,
	{ "ico" , _mime::image_ico } ,
	{ "txt" , _mime::text_plain } ,
	{ "html" , _mime::text_html } ,
	{ "htm" , _mime::text_html } ,
	{ "xml" , _mime::text_xml } ,
	{ "xhtml" , _mime::text_xml } ,
	{ "ini" , _mime::text_x_ini } ,
	{ "sav" , _mime::text_x_ini } ,
	{ "opt" , _mime::text_x_ini } ,
	{ "otf" , _mime::font_opentype } ,
	{ "ttf" , _mime::font_truetype } ,
	{ "mp3" , _mime::audio_mpeg } ,
	{ "wav" , _mime::audio_wav } ,
	{ "aif" , _mime::audio_x_aiff } ,
	{ "aifc" , _mime::audio_x_aiff } ,
	{ "aiff" , _mime::audio_x_aiff } ,
	{ "mid" , _mime::audio_x_midi } ,
	{ "midi" , _mime::audio_x_midi } ,
	{ "sav" , _mime::audio_x_mpegurl } ,
	{ "mod" , _mime::audio_x_mod } ,
	{ "exe" , _mime::application_octet_stream } ,
	{ "lua" , _mime::application_x_lua_bytecode } ,
	{ "msi" , _mime::application_microsoft_installer } ,
	{ "lnk" , _mime::application_x_ms_shortcut } ,
	{ "url" , _mime::application_x_internet_shortcut },
	{ "nds" , _mime::application_x_nintendo_ds_rom } ,
	{ "gba" , _mime::application_x_nintendo_gba_rom } ,
	{ "gbc" , _mime::application_x_nintendo_gba_rom } ,
	{ "bat" , _mime::application_x_nintendo_gba_rom } ,
	{ "reg" , _mime::application_x_ms_registry }
};

_toStr<_mime> mimeType2string = {
	{ _mime::directory , "directory" } , 
	{ _mime::image_jpeg , "image/jpeg" } , 
	{ _mime::image_png, "image/png" } ,
	{ _mime::image_gif, "image/gif" } ,
	{ _mime::image_bmp, "image/bmp" } ,
	{ _mime::image_ico, "image/ico" } ,
	{ _mime::text_plain, "text/plain" } ,
	{ _mime::text_html, "text/html" } ,
	{ _mime::text_xml , "text/xml" } ,
	{ _mime::font_opentype , "font/opentype" } ,
	{ _mime::font_truetype , "font/truetype" } ,
	{ _mime::audio_mpeg , "audio/mpeg" } ,
	{ _mime::audio_wav , "audio/wav" } ,
	{ _mime::audio_x_aiff , "audio/x-aiff" } ,
	{ _mime::audio_x_midi , "audio/x-midi" } ,
	{ _mime::audio_x_mpegurl , "audio/x-mpegurl" } ,
	{ _mime::audio_x_mod , "text/x-mod" } ,
	{ _mime::application_octet_stream , "application/octet-stream" } ,
	{ _mime::application_microsoft_installer , "application/microsoft-installer" } ,
	{ _mime::application_x_lua_bytecode , "application/x-lua-bytecode" } ,
	{ _mime::application_x_ms_shortcut , "application/x-ms-shortcut" } ,
	{ _mime::application_x_internet_shortcut , "application/x-internet-shortcut" } ,
	{ _mime::application_x_nintendo_ds_rom , "application/x-nintendo-ds-rom" } ,
	{ _mime::application_x_nintendo_gba_rom , "application/x-nintendo-gba-rom" } ,
	{ _mime::application_x_bat , "application/x-bat" } ,
	{ _mime::application_x_ms_registry , "application/x-ms-registry" }
};