#include "_type/type.gadget.type.h"

// Convert a gadgetType to a string
_map<_gadgetType,string> gadgetType2string = {
	{ _gadgetType::button , "button" },
	{ _gadgetType::stickybutton , "stickybutton" },
	{ _gadgetType::expandbutton , "expandbutton" },
	{ _gadgetType::label , "label" },
	{ _gadgetType::checkbox , "checkbox" },
	{ _gadgetType::calendar , "calendar" },
	{ _gadgetType::radiobox , "radiobox" },
	{ _gadgetType::textbox , "textbox" },
	{ _gadgetType::textarea , "textarea" },
	{ _gadgetType::selectbox , "selectbox" },
	{ _gadgetType::selectitem , "selectitem" },
	{ _gadgetType::progressbar , "progressbar" },
	{ _gadgetType::keyboard , "keyboard" },
	{ _gadgetType::desktop , "desktop" },
	{ _gadgetType::fileview , "fileview" },
	{ _gadgetType::fileobject , "fileobject" },
	{ _gadgetType::imagegadget , "imagegadget" },
	{ _gadgetType::scrollarea , "scrollarea" },
	{ _gadgetType::scrollbutton , "scrollbutton" },
	{ _gadgetType::scrollbar , "scrollbar" },
	{ _gadgetType::window , "window" },
	{ _gadgetType::screen , "screen" },
	{ _gadgetType::popup , "popup" },
	{ _gadgetType::slider , "slider" },
	{ _gadgetType::counter , "counter" },
	{ _gadgetType::contextmenu , "contextmenu" },
	{ _gadgetType::contextmenuentry , "contextmenuentry" },
	{ _gadgetType::resizehandle , "resizehandle" },
	{ _gadgetType::none , "none" }
};


_map<string,_gadgetType> string2gadgetType = {
	{ "button" , _gadgetType::button },
	{ "stickybutton" , _gadgetType::stickybutton },
	{ "expandbutton" , _gadgetType::expandbutton },
	{ "label" , _gadgetType::label },
	{ "checkbox" , _gadgetType::checkbox },
	{ "calendar" , _gadgetType::calendar },
	{ "radiobox" , _gadgetType::radiobox },
	{ "textbox" , _gadgetType::textbox },
	{ "textarea" , _gadgetType::textarea },
	{ "selectbox" , _gadgetType::selectbox },
	{ "selectitem" , _gadgetType::selectitem },
	{ "progressbar" , _gadgetType::progressbar },
	{ "keyboard" , _gadgetType::keyboard },
	{ "desktop" , _gadgetType::desktop },
	{ "fileview" , _gadgetType::fileview },
	{ "fileobject" , _gadgetType::fileobject },
	{ "imagegadget" , _gadgetType::imagegadget },
	{ "scrollarea" , _gadgetType::scrollarea },
	{ "scrollbutton" , _gadgetType::scrollbutton },
	{ "scrollbar" , _gadgetType::scrollbar },
	{ "window" , _gadgetType::window },
	{ "screen" , _gadgetType::screen },
	{ "popup" , _gadgetType::popup },
	{ "counter" , _gadgetType::counter },
	{ "slider" , _gadgetType::slider },
	{ "contextmenu" , _gadgetType::contextmenu },
	{ "contextmenuentry" , _gadgetType::contextmenuentry },
	{ "resizehandle" , _gadgetType::resizehandle },
	{ "none" , _gadgetType::none }
};